name: Update Plugin Version

on:
  repository_dispatch:
    types: [update-plugin-version]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Example Repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update Smart-Doc Version in pom.xml
        run: |
          version=${{ github.event.client_payload.version }}
          mvn versions:set-property -Dproperty=smart-doc.version -DnewVersion=$version -DgenerateBackupPoms=false

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add pom.xml
          git commit -m "chore(pom.xml): :arrow_up: update smart-doc version to ${{ github.event.client_payload.version }}"
          git push origin master
